"""Checkpoint 9. Chemistry inside the CP-SAT model.

The important test in this file is TestAgreesWithTheRulesEngine. Everything else
checks the model behaves; that one checks it believes the same things the
TypeScript engine believes, which is the property the whole architecture exists
to protect.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from fc_ai_solver import (
    ChemistryConfig,
    Manager,
    MissingChemistryRules,
    Pin,
    PoolCard,
    Requirement,
    SolveRequest,
    solve_single,
)

FIXTURES = Path(__file__).parent / "fixtures"
CROSSCHECK = json.loads((FIXTURES / "chemistry-crosscheck.json").read_text())
BASE_CONFIG = CROSSCHECK["chemistry_config"]


def config(**overrides) -> ChemistryConfig:
    merged = {**BASE_CONFIG, **overrides}
    return ChemistryConfig(**merged)


def card(card_id: str, **kwargs) -> PoolCard:
    defaults = dict(
        rating=84, positions=["CM"], nation=f"N-{card_id}", league=f"L-{card_id}",
        club=f"C-{card_id}", card_type="rare", quantity=1, cost=1,
    )
    defaults.update(kwargs)
    return PoolCard(id=card_id, **defaults)


def solve(pool, slots, **kwargs):
    return solve_single(SolveRequest(pool=pool, formation_slots=slots, **kwargs))


class TestTheServiceHoldsNoRules:
    """No defaults, no fallbacks, no guessing. A guess here mis-scores every squad
    containing the card and the tests stay green, which is the one failure mode
    worth being loud about."""

    def test_a_chemistry_requirement_without_rules_raises(self):
        pool = [card(f"c{i}") for i in range(11)]
        with pytest.raises(MissingChemistryRules, match="no chemistry rules were supplied"):
            solve(pool, ["CM"] * 11, requirements=[
                Requirement(type="teamChemistry", op="min", value=1),
            ])

    def test_an_unknown_card_type_raises_rather_than_defaulting(self):
        pool = [card(f"c{i}") for i in range(10)] + [card("new", card_type="winter_wildcard")]
        with pytest.raises(MissingChemistryRules, match="winter_wildcard"):
            solve(pool, ["CM"] * 11, chemistry=config())

    def test_a_card_type_supplied_in_the_config_is_accepted(self):
        contributions = dict(BASE_CONFIG["contributions"])
        contributions["winter_wildcard"] = {
            "club": 2, "league": 2, "nation": 2,
            "applies_league_to_all": False, "always_max_chem": False,
        }
        pool = [card(f"c{i}") for i in range(10)] + [card("new", card_type="winter_wildcard")]
        response = solve(pool, ["CM"] * 11, chemistry=config(contributions=contributions))
        assert response.status == "optimal"


class TestAgreesWithTheRulesEngine:
    """300 random squads scored by the TypeScript engine, pinned into this model,
    compared per player and in total. Generated by scripts/generate-chemistry-crosscheck.ts."""

    @pytest.mark.parametrize("case", CROSSCHECK["cases"], ids=lambda c: c["id"])
    def test_case(self, case):
        chem = dict(BASE_CONFIG)
        if case["manager"] is not None:
            chem["manager"] = Manager(**case["manager"])
        response = solve(
            [PoolCard(**c) for c in case["pool"]],
            case["formation_slots"],
            pins=[Pin(**p) for p in case["pins"]],
            chemistry=ChemistryConfig(**chem),
        )
        assert response.status in ("optimal", "feasible")
        by_slot = {p.slot_index: p.chemistry for p in response.placements}
        actual = [by_slot[i] for i in range(11)]
        assert actual == case["expected_player_chemistry"]
        assert response.squad_chemistry == case["expected_squad_chemistry"]


class TestThePositioningGate:
    def test_an_out_of_position_card_scores_nothing_and_counts_for_nothing(self):
        # Three clubmates are also three league mates, because a club sits in
        # exactly one league. So each holds club +1 and league +1, which is 2,
        # and the squad total is 6.
        pool = [card(f"a{i}", club="Alpha", league="League A") for i in range(3)]
        pool += [card(f"b{i}") for i in range(8)]
        slots = ["CM"] * 11

        both = solve(pool, slots, chemistry=config())
        assert both.squad_chemistry == 6

        # Make one of them unable to play any slot in this formation. It scores
        # nothing itself AND stops counting, so the club count falls to 2 and the
        # league count to 2. Club still clears its +1 step at 2, league does not
        # clear its +1 step until 3, so the survivors drop from 2 to 1 each.
        pool[2] = card("a2", club="Alpha", league="League A", positions=["GK"])
        misplaced = solve(pool, slots, chemistry=config())
        assert misplaced.squad_chemistry == 2
        # One misplacement, four chemistry gone, and only one of the four was its own.

    def test_an_icon_out_of_position_is_zero_not_three(self):
        pool = [card("icon", card_type="icon", club=None, league=None, positions=["ST"])]
        pool += [card(f"c{i}") for i in range(10)]
        response = solve(pool, ["CM"] * 11, pins=[Pin(card_id="icon", slot_index=0)],
                         chemistry=config())
        chem = {p.card_id: p.chemistry for p in response.placements}
        assert chem["icon"] == 0


class TestLaddersComeFromTheConfig:
    def test_changing_a_ladder_in_the_config_changes_the_answer(self):
        # Proof that nothing is baked in: move the league first step from 3 to 2
        # and a pair of league mates starts scoring.
        pool = [card(f"a{i}", league="Shared") for i in range(2)] + [card(f"b{i}") for i in range(9)]
        stock = solve(pool, ["CM"] * 11, chemistry=config())
        assert stock.squad_chemistry == 0

        loosened = solve(pool, ["CM"] * 11, chemistry=config(league_thresholds=[[8, 3], [5, 2], [2, 1]]))
        assert loosened.squad_chemistry == 2

    def test_icons_lift_every_league_not_one(self):
        pool = [card(f"pl{i}", league="Premier League") for i in range(7)]
        pool += [card("icon", card_type="icon", club=None, league=None)]
        pool += [card(f"z{i}") for i in range(3)]
        response = solve(pool, ["CM"] * 11, chemistry=config())
        chem = {p.card_id: p.chemistry for p in response.placements}
        # Seven league mates alone is +2. The Icon takes them to eight and +3.
        assert chem["pl0"] == 3
        assert chem["icon"] == 3


class TestChemistryRequirements:
    def test_team_chemistry_minimum_is_enforced(self):
        pool = [card(f"a{i}", club="Alpha", league="League A", nation="England") for i in range(11)]
        pool += [card(f"cheap{i}", cost=0) for i in range(11)]
        response = solve(pool, ["CM"] * 11, chemistry=config(), requirements=[
            Requirement(type="teamChemistry", op="min", value=33),
        ])
        assert response.status == "optimal"
        assert response.squad_chemistry >= 33

    def test_per_player_chemistry_is_not_the_same_as_the_total(self):
        # Ten linked cards plus one loner clears a total of 25 but fails a floor
        # of 1 on every player.
        pool = [card(f"a{i}", club="Alpha", league="League A") for i in range(10)]
        pool += [card("loner", cost=0)]
        slots = ["CM"] * 11

        total_only = solve(pool, slots, chemistry=config(), requirements=[
            Requirement(type="teamChemistry", op="min", value=20),
        ])
        assert total_only.status == "optimal"

        floor = solve(pool, slots, chemistry=config(), requirements=[
            Requirement(type="perPlayerChemistry", op="min", value=1),
        ])
        assert floor.status == "infeasible"

    def test_per_player_chemistry_with_a_count_only_needs_that_many(self):
        pool = [card(f"a{i}", club="Alpha", league="League A") for i in range(10)]
        pool += [card("loner", cost=0)]
        response = solve(pool, ["CM"] * 11, chemistry=config(), requirements=[
            Requirement(type="perPlayerChemistry", op="min", value=1, count=10),
        ])
        assert response.status == "optimal"


class TestManager:
    def test_a_manager_lifts_a_matching_player_by_one_and_no_more(self):
        pool = [card("italian", nation="Italy", league="Serie A")] + [card(f"c{i}") for i in range(10)]
        slots = ["CM"] * 11

        without = solve(pool, slots, chemistry=config())
        assert without.squad_chemistry == 0

        with_manager = solve(pool, slots, chemistry=config(
            manager=Manager(nation="Italy", league="Serie A")))
        chem = {p.card_id: p.chemistry for p in with_manager.placements}
        # Both nation and league match, and the bonus is still only +1.
        assert chem["italian"] == 1


class TestChemistryDrivesPlacement:
    def test_the_solver_places_cards_in_position_when_chemistry_demands_it(self):
        # Each card can play exactly one slot, and only the correct assignment
        # earns anything. The model has to find the matching, not just the cards.
        slots = ["GK", "LB", "CB", "CB", "RB", "LM", "CM", "CM", "RM", "ST", "ST"]
        pool = [
            card(f"a{i}", club="Alpha", league="League A", positions=[slot])
            for i, slot in enumerate(slots)
        ]
        response = solve(pool, slots, chemistry=config(), requirements=[
            Requirement(type="teamChemistry", op="min", value=33),
        ])
        assert response.status == "optimal"
        assert all(p.in_position for p in response.placements)
        assert response.squad_chemistry == 33
